apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels: { app: minio }
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: quay.io/minio/minio:latest
          args: ["server", "/data", "--console-address", ":9090"]
          env:
            - name: MINIO_REGION
              value: "us-east-1"
            - name: MINIO_ROOT_USER
              value: "minioadmin"
            - name: MINIO_ROOT_PASSWORD
              value: "minioadmin123"
          ports:
            - containerPort: 9000
            - containerPort: 9090
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minio-pvc

---

apiVersion: v1 
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  ports:
  - name: api 
    port: 9000 
    targetPort: 9000
  - name: console 
    port: 9090
    targetPort: 9090

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: minio-console
spec:
  to: { kind: Service, name: minio }
  port: { targetPort: 9090 }
  tls: { termination: edge }




