apiVersion: tekton.dev/v1
kind: PipelineRun

metadata:
  generateName: bank-model-ci-
  labels:
    app: bank-model-mlops

spec:

  # ----------------------------------------------------------
  # Pipeline to execute
  # ----------------------------------------------------------

  pipelineRef:
    name: bank-model-ci


  # ----------------------------------------------------------
  # Pipeline parameters
  # ----------------------------------------------------------

  params:

    # Replace with your actual Git repository URL
    - name: git-url
      value: "https://github.com/YOUR_USERNAME/OpenShift-AI-MLOps.git"

    # Git branch
    - name: git-revision
      value: "main"

    # Supported values:
    # fraud
    # loan
    - name: model-name
      value: "fraud"

    # Version that will be created in MinIO
    - name: model-version
      value: "1"

    # MinIO bucket
    - name: minio-bucket
      value: "models"


  # ----------------------------------------------------------
  # Shared workspace
  #
  # Git clone, training, conversion, validation and upload
  # all use this same PVC.
  # ----------------------------------------------------------

  workspaces:

    - name: shared-workspace

      volumeClaimTemplate:

        metadata:
          labels:
            app: bank-model-mlops

        spec:

          accessModes:
            - ReadWriteOnce

          resources:
            requests:
              storage: 2Gi
